name: Create Events on Discord

on:
  issues:
    types: [labeled]

jobs:
  reuse:
    if: contains( github.event.issue.labels.*.name, 'Approved' )
    uses: gitevents/propaganda/.github/workflows/discord-event.yml@main
    with:
      server-id: "855088264180400198"
      time-zone: 'Europe/Nicosia'
